language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

env:
  - SHA=$(git rev-parse --short=7 HEAD)

before_install:
  - |
    # build the image
    docker image build \
      --tag juliocesarmidia/envoy-proxy-01:$SHA \
      --tag juliocesarmidia/envoy-proxy-01:latest \
      -f ./envoy/envoy.Dockerfile ./envoy/

script:
  - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    docker image push juliocesarmidia/envoy-proxy-01:$SHA
    docker image push juliocesarmidia/envoy-proxy-01:latest
